# Generated by Django 5.1.6 on 2025-03-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'managed': False},
        ),
    ]
