# Generated by Django 5.1.6 on 2025-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shortenedurl',
            table='shortener_shortenedurl',
        ),
    ]
